### ISSUE TITLE
Unhandled Exception in ANetController.parseResponse

### ISSUE THREAD

**Issue by bwarlick** [ejamroz/Authorize.Net_XojoGateway#1]
I've got some issues going on in ANetController.parseResponse at the "return ParseJSON(json)" statement.  

First, the Try Catch statement is not working. I was able to fix it by changing "catch e as JSONException" to  "catch e as InvalidJSONException". Not a big deal. But the bigger issue is that ParseJSON is throwing an error even though the JSON is valid. I am wondering if this could be a Xojo Windows bug as I suspect the code is working fine on a Mac. 

Interestingly, I am able to get ParseJSON to work by removing the first 3 bytes of data from the content before converting the content to text. Here is the code:  
```
'remove the first three bytes of the memory block
Dim ContentFixed as New xojo.Core.MemoryBlock(content.size - 3)
ContentFixed = content.right(Content.size -3)
```
I'm interested to know if you see this issue or possibly it only affects Xojo Windows. I am assuming you are using Xojo Mac for development.

**Comment by ejamroz** [comment]
Thank you for the feedback on the try catch block. I made the change. I have also put up a new version that has a few other fixes in it. But, be warned, I had to change a couple function names so it will break a system that is using older versions.

To your question about parse json, I have only tested on mac, so it does seem to be operating system dependent. However, parseJSON() will through an invalidJSON exception if trying to parse valid json stored as text. I had to convert everything back to string for it to work properly. Not sure if that is related or not. I will look into into it though. Thank you.
